# Site settings
title: Nextree Consulting Co., LTD
email: wsro@nextree.co.kr
description: 나무소리 오픈을 위한 테스트 블로그 입니다.

baseurl:  # the subpath of your site, e.g. /blog/
url: "http://nextree.co.kr" # the base hostname & protocol for your site

github_username:  Wooseok7

# Build settings
markdown: redcarpet
pigments: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

highlighter: pygments

permalink: pretty

safe: true
lsi: true

gems:
  - jekyll-redirect-from
  - jemoji
