# Site settings
title: Nextree Consulting Co., LTD
email: wsro@nextree.co.kr
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "http://wooseok7.github.io/blog/" # the subpath of your site, e.g. /blog/
url: "http://nextree.co.kr" # the base hostname & protocol for your site

github_username:  Wooseok7

# Build settings
markdown: redcarpet
pigments: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

highlighter: pygments

permalink: pretty

safe: true
lsi: true

gems:
  - jekyll-redirect-from
  - jemoji
